version: '3'

services:
  mysql:
    build:
      context: docker/mysql
      dockerfile: Dockerfile
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=ent
    ports:
      - "3306:3306"